data:
  title_size: 30
  his_size: 50
  npratio: 4
  pop: 7
  fresh: 1
  
info:
  metrics:
  - auc
  - mrr
  - ndcg@5
  - ndcg@10

model:
  global: True
  attention_hidden_dim: 200
  word_emb_dim: 300
  dropout: 0.2
  head_num: 20
  head_dim: 20

train:
  seed: 42
  batch_size: 128
  epochs: 60
  learning_rate: 0.0001
  weight_decay: 0
